### ISSUE TITLE
Errro when access Admin->System->Configuration->Payment Methods

### ISSUE THREAD

**Issue by maxwhite** [DIBS-Payment-Services/Magento1_dibseasy#1]
On Magneto community edition there is error:

**Fatal error: Uncaught Error: Call to a member function toOptionArray() on boolean in app/code/core/Mage/Adminhtml/Block/System/Config/Form.php:463**
when access Admin->System->Configuration->Payment Methods
The problem in the file:
https://github.com/DIBS-Payment-Services/Magento1_dibseasy/blob/master/app/code/community/Dibs/EasyCheckout/etc/system.xml#L97
It works if I change **orderstatus/config_status_processing** to **adminhtml/system_config_source_order_status**

**Comment by TheisCorfixenVaimo** [comment]
Hi @maxwhite 

Thanks for the feedback, we have corrected this in the latest update.
