### ISSUE TITLE
while trying to checkout the following error will appear in exception.log

### ISSUE THREAD

**Issue by maxwhite** [DIBS-Payment-Services/Magento1_dibseasy#10]
Dibs_EasyPayment_Api_Exception_Request: Order amount not equal with items total amount in lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php:121
Stack trace:
#0 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php(62): Dibs_EasyPayment_Api_Service_Action_Payment_Create->validateRequest(Array)
#1 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Payment.php(53): Dibs_EasyPayment_Api_Service_Action_Payment_Create->request(Array)
#2 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/Model/Api.php(54): Dibs_EasyPayment_Api_Service_Payment->create(Array)
#3 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/Model/Checkout.php(50): Dibs_EasyCheckout_Model_Api->createPayment(Object(Mage_Sales_Model_Quote))
#4 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/controllers/CheckoutController.php(49): Dibs_EasyCheckout_Model_Checkout->createPaymentId(Object(Mage_Sales_Model_Quote))
#5 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Dibs_EasyCheckout_CheckoutController->indexAction()
#6 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#7 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/httpsdocs/mgnt/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#10 /var/www/httpsdocs/mgnt/index.php(82): Mage::run('', 'store')
#11 {main}

**Comment by maxwhite** [comment]
Sometimes it is hard to fix similar error because Magento has problems with rounding. It is possible to skip this type of validation because DIBS accepts orders with different amount (total and calculated). In that case customer will see notification about different amount, but order will be placed nevertheless

**Comment by TheisCorfixenVaimo** [comment]
Same error as in issue #11. Can you provide details on how this error happened, to see if this fixed have successfully fixed this problem as well?

**Comment by EasyByNets** [comment]
My colleague will update our module and test it. Thanks

**Comment by EasyByNets** [comment]
I still get an error, but have to wait for a colleague to find the log and sent it.

Do you instead have a demo shop that I can test from?

**Comment by EasyByNets** [comment]
This is the log error, looks like it's the same: 

ERR (3): Dibs_EasyPayment_Api_Exception_Request: Order amount not equal with items total amount in /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php:120 Stack trace: #0 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php(61): Dibs_EasyPayment_Api_Service_Action_Payment_Create->validateRequest(Array) #1 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Payment.php(53): Dibs_EasyPayment_Api_Service_Action_Payment_Create->request(Array) #2 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/Model/Api.php(54): Dibs_EasyPayment_Api_Service_Payment->create(Array) #3 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/Model/Checkout.php(50): Dibs_EasyCheckout_Model_Api->createPayment(Object(Mage_Sales_Model_Quote)) #4 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/controllers/CheckoutController.php(49): Dibs_EasyCheckout_Model_Checkout->createPaymentId(Object(Mage_Sales_Model_Quote)) #5 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Dibs_EasyCheckout_CheckoutController->indexAction() #6 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index') #7 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #8 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch() #9 /var/www/httpsdocs/mgnt/app/Mage.php(683): Mage_Core_Model_App->run(Array) #10 /var/www/httpsdocs/mgnt/index.php(82): Mage::run('', 'store') #11 {main}

**Comment by TheisCorfixenVaimo** [comment]
I will check if this check can be removed without affecting the rest of the module.

**Comment by TheisCorfixenVaimo** [comment]
Updated the repo to no longer have this validation included.
