### ISSUE TITLE
configure products fail

### ISSUE THREAD

**Issue by EasyByNets** [DIBS-Payment-Services/Magento1_dibseasy#11]
![pasted image at 2017_08_07 01_17 pm](https://user-images.githubusercontent.com/23499563/29354554-35da36b2-826e-11e7-9925-6299d76f58cd.png)

Found an issue when buying configurable products.

**Comment by TheisCorfixenVaimo** [comment]
Bug seems to be more related to the discount given to the cart, seems to be a type conversion error in PHP. I'm testing an update that should fix this issue.

**Comment by TheisCorfixenVaimo** [comment]
I updated the module to include a fix for this issue.
