### ISSUE TITLE
Transaction id must be presented in email confirmation receipt 

### ISSUE THREAD

**Issue by maxwhite** [DIBS-Payment-Services/Magento1_dibseasy#2]
Hi, 
could you please add transaction id to email confirmation receipt ? 
It should be like this: 
Payment ID: d7557845363628678977b97ea68aades
it is DIBS requirement. 
Thanks

**Comment by TheisCorfixenVaimo** [comment]
Hi @maxwhite 

We will look into this asap.

**Comment by leovaimo** [comment]
Payment ID was added to Payment Information.

**Comment by maxwhite** [comment]
Thanks, now it works !
