### ISSUE TITLE
Country data on order?

### ISSUE THREAD

**Issue by EasyByNets** [DIBS-Payment-Services/Magento1_dibseasy#3]
![screen_shot_2017-06-21_at_13_10_35](https://user-images.githubusercontent.com/23499563/27381936-03018de0-5685-11e7-8a43-24787d332a63.png)
Is it possible to add country and show country code for phone with a "+ "?

**Comment by TheisCorfixenVaimo** [comment]
We are working on this issue and will get back to you asap

**Comment by leovaimo** [comment]
Country field added to Billing and Shipping Address
