### ISSUE TITLE
Wrong live url

### ISSUE THREAD

**Issue by maxwhite** [DIBS-Payment-Services/Magento1_dibseasy#9]
live url should be changed to : https://api.dibspayment.eu
https://github.com/DIBS-Payment-Services/Magento1_dibseasy/blob/55de16f18be72ffa18c9965d20d3e5bd7f2ccbfc/lib/Dibs/EasyPayment/Api/Client.php#L15

**Comment by leovaimo** [comment]
Live Url Updated
